### ISSUE TITLE
Asynchronous Chunk getEntities call!

### ISSUE THREAD

**Issue by mocha666** [Glom-c/ItemSystem#1]
```java
[16:58:38 ERROR]: Could not pass event PacketSendEvent to ItemSystem v1.1.0
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2523) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1969) ~[?:?]
        at com.skillw.itemsystem.util.nms.NMSImpl.getEntity(NMSImpl.kt:178) ~[?:?]
        at com.skillw.itemsystem.internal.feature.listener.GlowListener.e(GlowListener.kt:30) ~[ItemSystem-1.1.0.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at com.skillw.itemsystem.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[ItemSystem-1.1.0.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1842]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.skillw.itemsystem.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:40) ~[ItemSystem-1.1.0.jar:?]
        at com.skillw.itemsystem.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:20) ~[ItemSystem-1.1.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at com.skillw.attributesystem.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:19) ~[AttributeSystem-1.4.2-fix.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:460) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:429) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:891) ~[?:?]

```
server version:
```
git-Purpur-1842 (MC: 1.19.2)*
 ```

**Comment by Glomzzz** [comment]
已修复
