### ISSUE TITLE
Bug | Purpur 1.19.2

### ISSUE THREAD

**Issue by Adriianh** [Glom-c/ItemSystem#2]
Occurs when someone connects to the server.

```
[19:16:29 ERROR]: Could not pass event PacketSendEvent to ItemSystem v1.0.3-20
java.lang.IllegalStateException: com.skillw.itemsystem.internal.feature.listener.SyncListener is not an instance of com.skillw.itemsystem.internal.feature.listener.SyncListener
        at com.skillw.itemsystem.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:36) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[ItemSystem.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.skillw.itemsystem.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:40) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:20) ~[ItemSystem.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:460) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:434) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.util.List (java.lang.Integer and java.util.List are in module java.base of loader 'bootstrap')
        at com.skillw.itemsystem.util.nms.NMSImpl.computeCraftItems(NMSImpl.kt:28) ~[?:?]
        at com.skillw.itemsystem.internal.feature.listener.SyncListener.dynamicItem(ItemListener.kt:23) ~[ItemSystem.jar:?]
        at com.skillw.itemsystem.internal.feature.listener.SyncListener.e2(ItemListener.kt:35) ~[ItemSystem.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at com.skillw.itemsystem.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[ItemSystem.jar:?]
        ... 32 more
```

**Comment by Glomzzz** [comment]
已修复
