### ISSUE TITLE
这是什么问题啊

### ISSUE THREAD

**Issue by 5tte** [Glom-c/ItemSystem#4]
[Netty Server IO #1/ERROR]: Could not pass event PacketSendEvent to ItemSystem v1.0.4-25
java.lang.NoClassDefFoundError: Could not initialize class com.skillw.itemsystem.internal.manager.ISConfig
	at com.skillw.itemsystem.internal.feature.listener.GlowListener.e(GlowListener.kt:29) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at com.skillw.itemsystem.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at com.skillw.itemsystem.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
	at com.skillw.itemsystem.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
	at com.skillw.itemsystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
	at com.skillw.itemsystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
	at com.skillw.itemsystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at com.skillw.itemsystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at com.skillw.itemsystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at com.skillw.itemsystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at com.skillw.itemsystem.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[aa.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at com.skillw.itemsystem.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:40) [ItemSystem-1.0.4-25%20(2).jar:?]
	at com.skillw.itemsystem.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:20) [ItemSystem-1.0.4-25%20(2).jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:200) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [aa.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Neige7** [comment]
ItemSystem在未来五个月将停止更新，尝试使用NeigeItems
MCBBS: https://www.mcbbs.net/thread-1364195-1-1.html
Github: https://github.com/Neige7/NeigeItems-Kotlin
Wiki: https://neige7.github.io/NeigeItems-Wiki-Docsify/

**Comment by Glomzzz** [comment]
同上，建议用ni
